version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - '8000:8000'
    restart: unless-stopped

  frontend:
    build:
      context: ./doc-analyzer-frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
    ports:
      - '3000:3000'
    depends_on:
      - backend
    restart: unless-stopped
